# Generated by Django 5.2.9 on 2026-01-19 19:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationRegulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the examination regulation (e.g., 'Computer Science B.Sc. 2020')", max_length=200)),
                ('version', models.CharField(help_text="Version identifier (e.g., '2020', 'v2.1')", max_length=50)),
                ('program', models.CharField(help_text='Degree program this regulation applies to', max_length=200)),
                ('total_credits_required', models.IntegerField(help_text='Total CP required for degree completion', validators=[django.core.validators.MinValueValidator(1)])),
                ('effective_date', models.DateField(help_text='Date when this regulation becomes effective')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this regulation is currently active')),
                ('description', models.TextField(blank=True, help_text='Additional description or notes about this regulation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Examination Regulation',
                'verbose_name_plural': 'Examination Regulations',
                'db_table': 'examination_regulations',
                'ordering': ['-effective_date', 'program'],
                'indexes': [models.Index(fields=['program', 'is_active'], name='examination_program_99209e_idx'), models.Index(fields=['effective_date'], name='examination_effecti_3bfb02_idx')],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('program', models.CharField(blank=True, help_text="Student's degree program (e.g., Computer Science B.Sc.)", max_length=200)),
                ('semester', models.IntegerField(blank=True, help_text='Current semester number', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('matriculation_number', models.CharField(blank=True, help_text='Student matriculation number (TU-ID)', max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('examination_regulation', models.ForeignKey(blank=True, help_text='The examination regulation version this student follows', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.examinationregulation')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField(help_text='Order of this milestone in the sequence (lower = earlier)')),
                ('type', models.CharField(choices=[('onboarding', 'Onboarding'), ('cp_threshold', 'Credit Point Threshold'), ('module_group', 'Module Group Completion'), ('deadline', 'Administrative Deadline'), ('career_goal', 'Career Goal Checkpoint'), ('thesis', 'Thesis Milestone'), ('completion', 'Degree Completion')], help_text='Type of milestone', max_length=50)),
                ('label', models.CharField(help_text='Short display label for the milestone', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the milestone and its requirements')),
                ('rule_payload', models.JSONField(blank=True, default=dict, help_text='JSON data defining completion rules (e.g., {cp_required: 30, modules: [...]})')),
                ('expected_by_semester', models.IntegerField(blank=True, help_text='Expected semester for completion (for on-track calculation)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('expected_by_date', models.DateField(blank=True, help_text='Expected date for completion (for deadline-based milestones)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('examination_regulation', models.ForeignKey(help_text='The regulation this milestone belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='api.examinationregulation')),
            ],
            options={
                'verbose_name': 'Milestone Definition',
                'verbose_name_plural': 'Milestone Definitions',
                'db_table': 'milestone_definitions',
                'ordering': ['examination_regulation', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('available', 'Available'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='locked', help_text='Current status of this milestone for the user', max_length=20)),
                ('achieved_at', models.DateTimeField(blank=True, help_text='Timestamp when the milestone was completed', null=True)),
                ('computed_explanation', models.TextField(blank=True, help_text="Auto-generated explanation of progress (e.g., '25/30 CP completed')")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone', models.ForeignKey(help_text='The milestone being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='api.milestonedefinition')),
                ('user', models.ForeignKey(help_text='The user whose progress is tracked', on_delete=django.db.models.deletion.CASCADE, related_name='milestone_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Milestone Progress',
                'verbose_name_plural': 'Milestone Progress',
                'db_table': 'milestone_progress',
                'ordering': ['user', 'milestone__order_index'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(help_text="Official module code (e.g., 'CS101', '20-00-0001')", max_length=50)),
                ('name', models.CharField(help_text='Module name', max_length=200)),
                ('credits', models.IntegerField(help_text='Credit points (CP/ECTS) for this module', validators=[django.core.validators.MinValueValidator(1)])),
                ('category', models.CharField(choices=[('mandatory', 'Mandatory'), ('elective', 'Elective'), ('specialization', 'Specialization'), ('interdisciplinary', 'Interdisciplinary'), ('thesis', 'Thesis')], default='mandatory', help_text='Module category/group', max_length=50)),
                ('group_name', models.CharField(blank=True, help_text="Optional group name for organizing modules (e.g., 'Foundations', 'Advanced CS')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Module description and learning objectives')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('examination_regulation', models.ForeignKey(help_text='The regulation this module belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.examinationregulation')),
                ('prerequisites', models.ManyToManyField(blank=True, help_text='Modules that must be completed before this one', related_name='required_for', to='api.module')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'modules',
                'ordering': ['module_code'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('milestone_reminder', 'Milestone Reminder'), ('deadline_warning', 'Deadline Warning'), ('milestone_achieved', 'Milestone Achieved'), ('recommendation', 'Recommendation'), ('support_service', 'Support Service Info'), ('system', 'System Notification')], help_text='Type of notification', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level', max_length=20)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message content')),
                ('due_at', models.DateTimeField(blank=True, help_text='Optional due date/time for deadline-based notifications', null=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when the notification was read', null=True)),
                ('action_url', models.CharField(blank=True, help_text="Optional URL for action button (e.g., '/roadmap', '/support-services')", max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_milestone', models.ForeignKey(blank=True, help_text='Optional related milestone', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='api.milestonedefinition')),
                ('user', models.ForeignKey(help_text='The user receiving this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the support service', max_length=200)),
                ('category', models.CharField(choices=[('academic', 'Academic Support'), ('career', 'Career Services'), ('counseling', 'Counseling'), ('administrative', 'Administrative'), ('financial', 'Financial Aid'), ('health', 'Health Services'), ('international', 'International Office'), ('other', 'Other')], help_text='Category of service', max_length=50)),
                ('description', models.TextField(help_text='Description of what the service provides')),
                ('contact_info', models.JSONField(blank=True, default=dict, help_text='Contact information (email, phone, office hours)')),
                ('url', models.URLField(blank=True, help_text='Website URL for the service')),
                ('location', models.CharField(blank=True, help_text='Physical location/building', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_milestones', models.ManyToManyField(blank=True, help_text='Milestones where this service is recommended', related_name='support_services', to='api.milestonedefinition')),
            ],
            options={
                'verbose_name': 'Support Service',
                'verbose_name_plural': 'Support Services',
                'db_table': 'support_services',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserModuleCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', help_text='Completion status', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Date when the module was completed', null=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=1, help_text='Final grade (e.g., 1.0, 2.3)', max_digits=3, null=True)),
                ('semester_taken', models.CharField(blank=True, help_text="Semester when module was taken (e.g., 'WS2023', 'SS2024')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(help_text='The module being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='user_completions', to='api.module')),
                ('user', models.ForeignKey(help_text='The user who completed or is taking the module', on_delete=django.db.models.deletion.CASCADE, related_name='module_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Module Completion',
                'verbose_name_plural': 'User Module Completions',
                'db_table': 'user_module_completions',
                'ordering': ['-completed_at', 'module__module_code'],
            },
        ),
        migrations.CreateModel(
            name='CareerGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('industry', 'Industry/Company'), ('research', 'Research/Academia'), ('startup', 'Startup/Entrepreneurship'), ('consulting', 'Consulting'), ('public_sector', 'Public Sector'), ('freelance', 'Freelance'), ('other', 'Other')], help_text='Type of career goal', max_length=50)),
                ('title', models.CharField(help_text='Brief title/description of the goal', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the career goal')),
                ('tags', models.JSONField(blank=True, default=list, help_text="Tags/keywords related to this goal (e.g., ['AI', 'Machine Learning'])")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this goal is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user who set this goal', on_delete=django.db.models.deletion.CASCADE, related_name='career_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Career Goal',
                'verbose_name_plural': 'Career Goals',
                'db_table': 'career_goals',
                'ordering': ['-is_active', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='career_goal_user_id_11b724_idx'), models.Index(fields=['goal_type'], name='career_goal_goal_ty_0fc0c3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='milestonedefinition',
            index=models.Index(fields=['examination_regulation', 'type'], name='milestone_d_examina_c49b81_idx'),
        ),
        migrations.AddIndex(
            model_name='milestonedefinition',
            index=models.Index(fields=['order_index'], name='milestone_d_order_i_a8c674_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='milestonedefinition',
            unique_together={('examination_regulation', 'order_index')},
        ),
        migrations.AddIndex(
            model_name='milestoneprogress',
            index=models.Index(fields=['user', 'status'], name='milestone_p_user_id_e52f3b_idx'),
        ),
        migrations.AddIndex(
            model_name='milestoneprogress',
            index=models.Index(fields=['milestone', 'status'], name='milestone_p_milesto_95f9ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='milestoneprogress',
            unique_together={('user', 'milestone')},
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['examination_regulation', 'category'], name='modules_examina_225b4c_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['module_code'], name='modules_module__b5e700_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('examination_regulation', 'module_code')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read_at'], name='notificatio_user_id_6c7360_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'type'], name='notificatio_user_id_6b5847_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['due_at'], name='notificatio_due_at_6f2b4d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx'),
        ),
        migrations.AddIndex(
            model_name='supportservice',
            index=models.Index(fields=['category', 'is_active'], name='support_ser_categor_cf85f5_idx'),
        ),
        migrations.AddIndex(
            model_name='usermodulecompletion',
            index=models.Index(fields=['user', 'status'], name='user_module_user_id_b8af99_idx'),
        ),
        migrations.AddIndex(
            model_name='usermodulecompletion',
            index=models.Index(fields=['module', 'status'], name='user_module_module__8efe61_idx'),
        ),
        migrations.AddIndex(
            model_name='usermodulecompletion',
            index=models.Index(fields=['completed_at'], name='user_module_complet_8aede4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usermodulecompletion',
            unique_together={('user', 'module')},
        ),
    ]
