# Generated by Django 5.2.9 on 2025-12-14 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='status',
        ),
        migrations.RemoveField(
            model_name='module',
            name='student',
        ),
        migrations.AlterField(
            model_name='student',
            name='credits_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('done', 'Abgeschlossen'), ('in_progress', 'In Bearbeitung'), ('open', 'Offen')], default='open', max_length=20)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='api.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to='api.student')),
            ],
            options={
                'unique_together': {('student', 'module')},
            },
        ),
    ]
