# Generated by Django 5.2.9 on 2026-02-04 15:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_id', models.CharField(help_text="Unique identifier for the career (e.g., 'software_engineer')", max_length=100, unique=True)),
                ('title_en', models.CharField(help_text='English title of the career', max_length=200)),
                ('title_de', models.CharField(help_text='German title of the career', max_length=200)),
                ('description_en', models.TextField(blank=True, help_text='English description of the career')),
                ('description_de', models.TextField(blank=True, help_text='German description of the career')),
                ('salary_junior', models.IntegerField(blank=True, help_text='Average junior salary in EUR', null=True)),
                ('salary_mid', models.IntegerField(blank=True, help_text='Average mid-level salary in EUR', null=True)),
                ('salary_senior', models.IntegerField(blank=True, help_text='Average senior salary in EUR', null=True)),
                ('required_skills', models.JSONField(blank=True, default=list, help_text='List of required skills for this career')),
                ('icon', models.CharField(blank=True, help_text='Icon name or emoji for the career', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this career path is currently displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Career Path',
                'verbose_name_plural': 'Career Paths',
                'db_table': 'career_paths',
                'ordering': ['title_en'],
            },
        ),
        migrations.AddField(
            model_name='module',
            name='duration_semesters',
            field=models.IntegerField(default=1, help_text='Duration in semesters'),
        ),
        migrations.AddField(
            model_name='module',
            name='exam_form',
            field=models.TextField(blank=True, help_text='Examination form and requirements'),
        ),
        migrations.AddField(
            model_name='module',
            name='language',
            field=models.CharField(default='Deutsch', help_text='Teaching language', max_length=50),
        ),
        migrations.AddField(
            model_name='module',
            name='learning_content',
            field=models.TextField(blank=True, help_text='Detailed learning content and topics covered'),
        ),
        migrations.AddField(
            model_name='module',
            name='learning_objectives',
            field=models.TextField(blank=True, help_text='Learning objectives and outcomes'),
        ),
        migrations.AddField(
            model_name='module',
            name='name_en',
            field=models.CharField(blank=True, help_text='Module name (English)', max_length=200),
        ),
        migrations.AddField(
            model_name='module',
            name='offering_frequency',
            field=models.CharField(blank=True, help_text="How often the module is offered (e.g., 'Jedes Semester')", max_length=100),
        ),
        migrations.AddField(
            model_name='module',
            name='prerequisites_text',
            field=models.TextField(blank=True, help_text='Prerequisites as text description'),
        ),
        migrations.AddField(
            model_name='module',
            name='self_study_hours',
            field=models.IntegerField(blank=True, help_text='Self-study hours', null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='workload_hours',
            field=models.IntegerField(blank=True, help_text='Total workload in hours', null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, help_text='Module description (short)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(help_text='Module name (German)', max_length=200),
        ),
        migrations.CreateModel(
            name='ModuleCareerRelevance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.IntegerField(help_text='Relevance score from 0-100 (higher = more relevant)', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_core', models.BooleanField(default=False, help_text='Whether this is a core/essential module for the career')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career_path', models.ForeignKey(help_text='The career path', on_delete=django.db.models.deletion.CASCADE, related_name='module_relevances', to='api.careerpath')),
                ('module', models.ForeignKey(help_text='The module', on_delete=django.db.models.deletion.CASCADE, related_name='career_relevances', to='api.module')),
            ],
            options={
                'verbose_name': 'Module Career Relevance',
                'verbose_name_plural': 'Module Career Relevances',
                'db_table': 'module_career_relevance',
                'ordering': ['-relevance_score'],
                'indexes': [models.Index(fields=['career_path', 'relevance_score'], name='module_care_career__15fe17_idx'), models.Index(fields=['module', 'relevance_score'], name='module_care_module__c1755f_idx')],
                'unique_together': {('module', 'career_path')},
            },
        ),
        migrations.CreateModel(
            name='UserCareerInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_level', models.IntegerField(default=50, help_text='Interest level from 0-100', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_primary', models.BooleanField(default=False, help_text="Whether this is the user's primary career interest")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career_path', models.ForeignKey(help_text='The career path of interest', on_delete=django.db.models.deletion.CASCADE, related_name='interested_users', to='api.careerpath')),
                ('user', models.ForeignKey(help_text='The user', on_delete=django.db.models.deletion.CASCADE, related_name='career_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Career Interest',
                'verbose_name_plural': 'User Career Interests',
                'db_table': 'user_career_interests',
                'ordering': ['-interest_level', '-is_primary'],
                'unique_together': {('user', 'career_path')},
            },
        ),
    ]
