# Generated by Django 5.2.8 on 2026-02-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_de', models.CharField(help_text='German title', max_length=300)),
                ('title_en', models.CharField(help_text='English title', max_length=300)),
                ('provider', models.CharField(help_text="e.g., 'TU Darmstadt: Dezernat Internationales'", max_length=200)),
                ('category', models.CharField(choices=[('berufseinstieg', 'Berufseinstieg / Career Entry'), ('studienerfolg', 'Studienerfolg / Study Success'), ('integration', 'Integration, Sprache und Unterstützung')], max_length=50)),
                ('description_de', models.TextField(help_text='German description from PDF')),
                ('description_en', models.TextField(help_text='English description from PDF')),
                ('relevance_reason_de', models.TextField(help_text='Why relevant (German)')),
                ('relevance_reason_en', models.TextField(help_text='Why relevant (English)')),
                ('links', models.JSONField(blank=True, default=list, help_text="List of URLs: ['https://...', 'https://...']")),
                ('contact_emails', models.JSONField(blank=True, default=list, help_text="List of emails: ['email@example.com']")),
                ('career_fields', models.JSONField(default=list, help_text="Array of applicable career fields: ['industry', 'research', ...]")),
                ('source', models.CharField(default='PM-approved (yellow-highlighted)', help_text='Source tracking', max_length=100)),
                ('priority', models.IntegerField(default=0, help_text='Display order (higher = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Career Offer',
                'verbose_name_plural': 'Career Offers',
                'db_table': 'career_offers',
                'ordering': ['-priority', 'category', 'title_de'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='career_offe_categor_9600bf_idx')],
            },
        ),
    ]
