# Generated by Django 5.2.9 on 2026-02-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_careerpath_module_duration_semesters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='category',
            field=models.CharField(choices=[('Pflichtbereich', 'Pflichtbereich'), ('Wahlpflichtbereich', 'Wahlpflichtbereich'), ('Informatik-Wahlbereich', 'Informatik-Wahlbereich'), ('Studienbegleitende Leistungen', 'Studienbegleitende Leistungen'), ('Studium Generale', 'Studium Generale'), ('Abschlussbereich', 'Abschlussbereich')], default='Wahlpflichtbereich', help_text='Module category/group', max_length=50),
        ),
    ]
