# Generated by Django 5.2.9 on 2026-02-09 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_careeroffer'),
        ('api', '0003_alter_module_category'),
    ]

    operations = [
    ]
