# Generated by Django 5.2.9 on 2026-02-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_0002_careeroffer_0003_alter_module_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official program name', max_length=200)),
                ('language_of_instruction', models.CharField(choices=[('German', 'German'), ('English', 'English')], help_text='Primary language of instruction', max_length=20)),
                ('specializations', models.JSONField(blank=True, default=list, help_text='List of specialization tracks available in this program')),
                ('url', models.URLField(help_text='Official TU Darmstadt program page URL')),
                ('description_en', models.TextField(blank=True, help_text='Short description (English)')),
                ('description_de', models.TextField(blank=True, help_text='Short description (German)')),
                ('order_index', models.IntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master Program',
                'verbose_name_plural': 'Master Programs',
                'db_table': 'master_programs',
                'ordering': ['order_index', 'name'],
            },
        ),
    ]
