from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

# Create a router and register our viewsets with it
router = DefaultRouter()
router.register(r'students', views.StudentViewSet, basename='student')
router.register(r'modules', views.ModuleViewSet, basename='module')
router.register(r'progress', views.ModuleProgressViewSet, basename='progress')

# The API URLs are now determined automatically by the router
urlpatterns = [
    # Test endpoint
    path("hello/", views.hello_world, name="hello"),

    # Include all router-generated URLs
    path("", include(router.urls)),
]

# Available endpoints (automatically generated by router):
#
# Students:
# - GET    /api/students/              - List all students
# - POST   /api/students/              - Create a new student
# - GET    /api/students/{id}/         - Retrieve a specific student
# - PUT    /api/students/{id}/         - Update a student (full)
# - PATCH  /api/students/{id}/         - Update a student (partial)
# - DELETE /api/students/{id}/         - Delete a student
# - GET    /api/students/{id}/progress/ - Get student's module progress
# - GET    /api/students/{id}/stats/   - Get student's statistics
#
# Modules:
# - GET    /api/modules/               - List all modules
# - POST   /api/modules/               - Create a new module
# - GET    /api/modules/{id}/          - Retrieve a specific module
# - PUT    /api/modules/{id}/          - Update a module (full)
# - PATCH  /api/modules/{id}/          - Update a module (partial)
# - DELETE /api/modules/{id}/          - Delete a module
# - GET    /api/modules/summary/       - Get module statistics
#
# Module Progress:
# - GET    /api/progress/              - List all progress records (supports ?student_id=X and ?status=Y)
# - POST   /api/progress/              - Create a new progress record
# - GET    /api/progress/{id}/         - Retrieve a specific progress record
# - PUT    /api/progress/{id}/         - Update a progress record (full)
# - PATCH  /api/progress/{id}/         - Update a progress record (partial)
# - DELETE /api/progress/{id}/         - Delete a progress record
# - GET    /api/progress/by_status/    - Get progress records grouped by status
