services:
  backend:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./docs:/docs
    command: >
      sh -c "
      pip install -r requirements.txt &&
      python manage.py migrate &&
      python manage.py import_course_data --modules-file /docs/data-model/modules_cleaned.json --careers-file /docs/data-model/career_paths.json &&
      python manage.py seed_career_offers &&
      python manage.py seed_master_programs &&
      python manage.py runserver 0.0.0.0:8000
      "
    networks:
      - internal-web
      - tpse31-internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=internal-web"
      - "traefik.http.routers.tpse31-fec-api.rule=Host(`fec-roadmap.precis.tu-darmstadt.de`) && PathPrefix(`/api`)"
      - "traefik.http.routers.tpse31-fec-api.entrypoints=websecure"
      - "traefik.http.routers.tpse31-fec-api.tls=true"
      - "traefik.http.services.tpse31-fec-api.loadbalancer.server.port=8000"

      - "traefik.http.routers.tpse31-fec-admin.rule=Host(`fec-roadmap.precis.tu-darmstadt.de`) && PathPrefix(`/admin`)"
      - "traefik.http.routers.tpse31-fec-admin.entrypoints=websecure"
      - "traefik.http.routers.tpse31-fec-admin.tls=true"
      - "traefik.http.services.tpse31-fec-admin.loadbalancer.server.port=8000"

      - "traefik.http.routers.tpse31-fec-static.rule=Host(`fec-roadmap.precis.tu-darmstadt.de`) && PathPrefix(`/static`)"
      - "traefik.http.routers.tpse31-fec-static.entrypoints=websecure"
      - "traefik.http.routers.tpse31-fec-static.tls=true"
      - "traefik.http.services.tpse31-fec-static.loadbalancer.server.port=8000"
    restart: unless-stopped

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app:delegated
      - frontend_node_modules:/app/node_modules
    command: >
      sh -c "
      npm install &&
      npm run build &&
      npm install -g serve &&
      serve -s build -l 3000
      "
    environment:
      - REACT_APP_API_URL=https://fec-roadmap.precis.tu-darmstadt.de/api
      - HOST=0.0.0.0
      - PORT=3000
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    networks:
      - internal-web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=internal-web"
      - "traefik.http.services.tpse31-fec-frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.tpse31-fec.rule=Host(`fec-roadmap.precis.tu-darmstadt.de`)"
      - "traefik.http.routers.tpse31-fec.entrypoints=websecure"
      - "traefik.http.routers.tpse31-fec.tls=true"
      - "traefik.http.routers.tpse31-fec.service=tpse31-fec-frontend"
      - "traefik.http.routers.tpse31-fec.priority=1"
    restart: unless-stopped

networks:
  internal-web:
    external: true
    name: internal-web
  tpse31-internal:
    driver: bridge
volumes:
  frontend_node_modules:
